example.property= I AM THE dev
eureka.client.service-url.defaultZone=http://eureka-service:8070/eureka/

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/inventorydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=DEBUG

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=${spring.application.name}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=true

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.type.mapping=stockReserved:com.gcg.inventoryservice.event.StockReservedEvent,stockReservationFailed:com.gcg.inventoryservice.event.StockReservationFailedEvent
spring.kafka.consumer.properties.spring.json.type.mapping=orderCreated:com.gcg.inventoryservice.event.OrderCreatedEvent,paymentCompleted:com.gcg.inventoryservice.event.PaymentCompletedEvent,paymentFailed:com.gcg.inventoryservice.event.PaymentFailedEvent

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60000

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]