example.property= I AM THE dev
eureka.client.service-url.defaultZone=http://eureka-service:8070/eureka/

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect